services:
  mongodb:
    image: mongo:7.0
    container_name: mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoshortener
      MONGO_INITDB_ROOT_PASSWORD: mongoshortenerpwd
      MONGO_INITDB_DATABASE: urlshortener
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - mongodbdata:/data/db
    ports:
      - "27017:27017"

  urlshortener_cli:
    build:
      dockerfile: ./urlshortener_cli/Dockerfile
    image: urlshortener
    profiles: ['urlshortener_cli']

volumes:
  mongodbdata:
    driver: local